#pragma once

enum PacketType {
    PT_Unknown0,
    PT_ResetSequence,
    PT_Unknown2,
    PT_Crypto,
    PT_Normal
};

enum ControlPacketOpcode {
    // OPCODES 0x00-0F
    OP_HandleGamePacket,
    OP_ClientStart,
    OP_ServerStart,
    OP_MultiPacket,
    OP_Unk4,
    OP_TeardownConnection,
    OP_Unk6,
    OP_ControlSync,
    // 0x08
    OP_ControlSyncResp,
    OP_SlottedMetaPacket0,
    OP_SlottedMetaPacket1,
    OP_SlottedMetaPacket2,
    OP_SlottedMetaPacket3,
    OP_SlottedMetaPacket4,
    OP_SlottedMetaPacket5,
    OP_SlottedMetaPacket6,

    // OPCODES 0x10-1F
    OP_SlottedMetaPacket7,
    OP_RelatedA0,
    OP_RelatedA1,
    OP_RelatedA2,
    OP_RelatedA3,
    OP_RelatedB0,
    OP_RelatedB1,
    OP_RelatedB2,
    // 0x18
    OP_RelatedB3,
    OP_MultiPacketEx,
    OP_Unk26,
    OP_Unk27,
    OP_Unk28,
    OP_ConnectionClose,
    OP_Unk30
};

enum GamePacketOpcode {
    // OPCODES 0x00-0F
    OP_Unknown0,
    OP_LoginMessage,
    OP_LoginRespMessage,
    OP_ConnectToWorldRequestMessage, // found by searching for 83 F8 03 89 in IDA
    OP_ConnectToWorldMessage,
    OP_VNLWorldStatusMessage,
    OP_UnknownMessage6,
    OP_UnknownMessage7,
    // 0x08
    OP_PlayerStateMessage,
    OP_HitMessage,
    OP_HitHint,
    OP_DamageMessage,
    OP_DestroyMessage,
    OP_ReloadMessage,
    OP_MountVehicleMsg,
    OP_DismountVehicleMsg,

    // OPCODES 0x10-1F
    OP_UseItemMessage,
    OP_MoveItemMessage,
    OP_ChatMsg,
    OP_CharacterNoRecordMessage,
    OP_CharacterInfoMessage,
    OP_UnknownMessage21,
    OP_BindPlayerMessage,
    OP_ObjectCreateMessage_Duplicate,
    // 0x18
    OP_ObjectCreateMessage,
    OP_ObjectDeleteMessage,
    OP_PingMsg,
    OP_VehicleStateMessage,
    OP_FrameVehicleStateMessage,
    OP_GenericObjectStateMsg,
    OP_ChildObjectStateMessage,
    OP_ActionResultMessage,

    // OPCODES 0x20-2F
    OP_UnknownMessage32,
    OP_ActionProgressMessage,
    OP_ActionCancelMessage,
    OP_ActionCancelAcknowledgeMessage,
    OP_SetEmpireMessage,
    OP_EmoteMsg,
    OP_UnuseItemMessage,
    OP_ObjectDetachMessage,
    // 0x28
    OP_CreateShortcutMessage,
    OP_ChangeShortcutBankMessage,
    OP_ObjectAttachMessage,
    OP_UnknownMessage43,
    OP_PlanetsideAttributeMessage,
    OP_RequestDestroyMessage,
    OP_UnknownMessage46,
    OP_CharacterCreateRequestMessage,

    // OPCODES 0x30-3F
    OP_CharacterRequestMessage,
    OP_LoadMapMessage,
    OP_SetCurrentAvatarMessage,
    OP_ObjectHeldMessage,
    OP_WeaponFireMessage,
    OP_AvatarJumpMessage,
    OP_PickupItemMessage,
    OP_DropItemMessage,
    // 0x38
    OP_InventoryStateMessage,
    OP_ChangeFireStateMessage_Start,
    OP_ChangeFireStateMessage_Stop,
    OP_UnknownMessage59,
    OP_GenericCollisionMsg,
    OP_QuantityUpdateMessage,
    OP_ArmorChangedMessage,
    OP_ProjectileStateMessage,

    // OPCODES 0x40-4F
    OP_MountVehicleCargoMsg,
    OP_DismountVehicleCargoMsg,
    OP_CargoMountPointStatusMessage,
    OP_BeginZoningMessage,
    OP_ItemTransactionMessage,
    OP_ItemTransactionResultMessage,
    OP_ChangeFireModeMessage,
    OP_ChangeAmmoMessage,
    // 0x48
    OP_TimeOfDayMessage,
    OP_UnknownMessage73,
    OP_SpawnRequestMessage,
    OP_DeployRequestMessage,
    OP_UnknownMessage76,
    OP_RepairMessage,
    OP_ServerVehicleOverrideMsg,
    OP_LashMessage,

    // OPCODES 0x50-5F
    OP_TargetingInfoMessage,
    OP_TriggerEffectMessage,
    OP_WeaponDryFireMessage,
    OP_DroppodLaunchRequestMessage,
    OP_HackMessage,
    OP_DroppodLaunchResponseMessage,
    OP_GenericObjectActionMessage,
    OP_AvatarVehicleTimerMessage,
    // 0x58
    OP_AvatarImplantMessage,
    OP_UnknownMessage89,
    OP_DelayedPathMountMsg,
    OP_OrbitalShuttleTimeMsg,
    OP_AIDamage,
    OP_DeployObjectMessage,
    OP_FavoritesRequest,
    OP_FavoritesResponse,

    // OPCODES 0x60-6F
    OP_FavoritesMessage,
    OP_ObjectDetectedMessage,
    OP_SplashHitMessage,
    OP_SetChatFilterMessage,
    OP_AvatarSearchCriteriaMessage,
    OP_AvatarSearchResponse,
    OP_WeaponJammedMessage,
    OP_LinkDeadAwarenessMsg,
    // 0x68
    OP_DroppodFreefallingMessage,
    OP_AvatarFirstTimeEventMessage,
    OP_AggravatedDamageMessage,
    OP_TriggerSoundMessage,
    OP_LootItemMessage,
    OP_VehicleSubStateMessage,
    OP_SquadMembershipRequest,
    OP_SquadMembershipResponse,

    // OPCODES 0x70-7F
    OP_SquadMemberEvent,
    OP_PlatoonEvent,
    OP_FriendsRequest,
    OP_FriendsResponse,
    OP_TriggerEnvironmentalDamageMessage,
    OP_TrainingZoneMessage,
    OP_DeployableObjectsInfoMessage,
    OP_SquadState,
    // 0x78
    OP_OxygenStateMessage,
    OP_TradeMessage,
    OP_UnknownMessage122,
    OP_DamageFeedbackMessage,
    OP_DismountBuildingMsg,
    OP_UnknownMessage125,
    OP_UnknownMessage126,
    OP_AvatarStatisticsMessage,

    // OPCODES 0x80-8F
    OP_GenericObjectAction2Message,
    OP_DestroyDisplayMessage,
    OP_TriggerBotAction,
    OP_SquadWaypointRequest,
    OP_SquadWaypointEvent,
    OP_OffshoreVehicleMessage,
    OP_ObjectDeployedMessage,
    OP_ObjectDeployedCountMessage,
    // 0x88
    OP_WeaponDelayFireMessage,
    OP_BugReportMessage,
    OP_PlayerStasisMessage,
    OP_UnknownMessage139,
    OP_OutfitMembershipRequest,
    OP_OutfitMembershipResponse,
    OP_OutfitRequest,
    OP_OutfitEvent,

    // OPCODES 0x90-9F
    OP_OutfitMemberEvent,
    OP_OutfitMemberUpdate,
    OP_PlanetsideStringAttributeMessage,
    OP_DataChallengeMessage,
    OP_DataChallengeMessageResp,
    OP_WeatherMessage,
    OP_SimDataChallenge,
    OP_SimDataChallengeResp,
    // 0x98
    OP_OutfitListEvent,
    OP_EmpireIncentivesMessage,
    OP_InvalidTerrainMessage,
    OP_SyncMessage,
    OP_DebugDrawMessage,
    OP_SoulMarkMessage,
    OP_UplinkPositionEvent,
    OP_HotSpotUpdateMessage,

    // OPCODES 0xA0-AF
    OP_BuildingInfoUpdateMessage,
    OP_FireHintMessage,
    OP_UplinkRequest,
    OP_UplinkResponse,
    OP_WarpgateRequest,
    OP_WarpgateResponse,
    OP_DamageWithPositionMessage,
    OP_GenericActionMessage,
    // 0xA8
    OP_ContinentalLockUpdateMessage,
    OP_AvatarGrenadeStateMessage,
    OP_UnknownMessage170,
    OP_UnknownMessage171,
    OP_ReleaseAvatarRequestMessage,
    OP_AvatarDeadStateMessage,
    OP_CSAssistMessage,
    OP_CSAssistCommentMessage,

    // OPCODES 0xB0-BF
    OP_VoiceHostRequest,
    OP_VoiceHostKill,
    OP_VoiceHostInfo,
    OP_BattleplanMessage,
    OP_BattleExperienceMessage,
    OP_TargetingImplantRequest,
    OP_ZonePopulationUpdateMessage,
    OP_DisconnectMessage,
    // 0xB8
    OP_ExperienceAddedMessage,
    OP_OrbitalStrikeWaypointMessage,
    OP_KeepAliveMessage,
    OP_MapObjectStateBlockMessage,
    OP_SnoopMsg,
    OP_PlayerStateMessageUpstream,
    OP_PlayerStateShiftMessage,
    OP_ZipLineMessage,

    // OPCODES 0xC0-CF
    OP_CaptureFlagUpdateMessage,
    OP_VanuModuleUpdateMessage,
    OP_FacilityBenefitShieldChargeRequestMessage,
    OP_ProximityTerminalUseMessage,
    OP_QuantityDeltaUpdateMessage,
    OP_ChainLashMessage,
    OP_ZoneInfoMessage,
    OP_LongRangeProjectileInfoMessage,
    // 0xC8
    OP_WeaponLazeTargetPositionMessage,
    OP_ModuleLimitsMessage,
    OP_OutfitBenefitMessage,
    OP_EmpireChangeTimeMessage,
    OP_ClockCalibrationMessage,
    OP_DensityLevelUpdateMessage,
    OP_ActOfGodMessage,
    OP_AvatarAwardMessage,

    // OPCODES 0xD0-DF
    OP_UnknownMessage208,
    OP_DisplayedAwardMessage,
    OP_RespawnAMSInfoMessage,
    OP_ComponentDamageMessage,
    OP_GenericObjectActionAtPositionMessage,
    OP_PropertyOverrideMessage,
    OP_WarpgateLinkOverrideMessage,
    OP_EmpireBenefitsMessage,
    // 0xD8
    OP_ForceEmpireMessage,
    OP_BroadcastWarpgateUpdateMessage,
    OP_UnknownMessage218,
    OP_SquadMainTerminalMessage,
    OP_SquadMainTerminalResponseMessage,
    OP_SquadOrderMessage,
    OP_SquadOrderResponse,
    OP_ZoneLockInfoMessage,

    // OPCODES 0xE0-EF
    OP_SquadBindInfoMessage,
    OP_AudioSequenceMessage,
    OP_SquadFacilityBindInfoMessage,
    OP_ZoneForcedCavernConnectionsMessage,
    OP_MissionActionMessage,
    OP_MissionKillTriggerMessage,
    OP_ReplicationStreamMessage,
    OP_SquadDefinitionActionMessage,
    // 0xE8
    OP_SquadDetailDefinitionUpdateMessage,
    OP_TacticsMessage,
    OP_RabbitUpdateMessage,
    OP_SquadInvitationRequestMessage,
    OP_CharacterKnowledgeMessage,
    OP_GameScoreUpdateMessage,
    OP_UnknownMessage238,
    OP_OrderTerminalBugMessage,

    // OPCODES 0xF0-F3
    OP_QueueTimedHelpMessage,
    OP_MailMessage,
    OP_GameVarUpdate,
    OP_ClientCheatedMessage // last known message type (243, 0xF3)
};
